#cloud-config
autoinstall:
  version: 1
  locale: pt_BR
  keyboard:
    layout: br
  timezone: America/Fortaleza
  identity:
    hostname: ubuntu-dev
    username: devuser
    password: "$6$TEXTOHASH"  # Substitua pelo hash da senha
  ssh:
    install-server: true
    authorized-keys: []
  storage:
    layout:
      name: custom
    config:
      - type: disk
        id: disk0
        match:
          size: 100000000000  # 100 GB
        wipe: superblock-recursive

      - type: partition
        id: boot
        device: disk0
        size: 1G
        flag: boot

      - type: partition
        id: root
        device: disk0
        size: 45G

      - type: partition
        id: home
        device: disk0
        size: 50G

      - type: partition
        id: swap
        device: disk0
        size: 4G

      - type: format
        id: boot-format
        volume: boot
        fstype: ext4

      - type: format
        id: root-format
        volume: root
        fstype: ext4

      - type: format
        id: home-format
        volume: home
        fstype: ext4

      - type: format
        id: swap-format
        volume: swap
        fstype: swap

      - type: mount
        id: boot-mount
        path: /boot
        device: boot-format

      - type: mount
        id: root-mount
        path: /
        device: root-format

      - type: mount
        id: home-mount
        path: /home
        device: home-format

      - type: mount
        id: swap-mount
        path: none
        device: swap-format
        swap: true
  packages:
    - build-essential
    - git
    - curl
    - vim
    - docker.io
    - docker-compose
    - python3
    - python3-pip
    - nodejs
    - npm
    - openjdk-17-jdk
  user-data:
    disable_root: false
  late-commands:
    - curtin in-target --target=/target -- usermod -aG docker devuser

